### PR TITLE
Drive letters

### PR DESCRIPTION
**Pull request by arekbulski**

### CODE REVIEW

**Comment by arekbulski** [comment]
Pull request ended up with all the changes that I submitted to the main repository. I need some tutoring in Git.  :disappointed:

**Comment by Liryna** [comment]
@arekbulski I think you created the pull request to the wrong repository :(

**Comment by arekbulski** [comment]
Yeah. :disappointed:

**Comment by arekbulski** [comment]
You can see the changes to __init__, maybe work it out yourself?

**Comment by Liryna** [comment]
you mean testing it or review the coments ?

**Comment by arekbulski** [comment]
How can I send you a patch? I cannot fork your repo, I already forked the original repo.

**Comment by Liryna** [comment]
Do you want to apply the commit https://github.com/Liryna/pyfilesystem/pull/1/commits/0117ff7729d6fdf4c73fd27ba2c48ad399ded3df on my changes ?
If you use tortoise git, you can create a patch easily https://tortoisegit.org/docs/tortoisegit/tgit-dug-patch.html

**Pull request closed without merging**
